services:
  web:
    build: .
    container_name: horizon-search
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TRANSFORMERS_CACHE=/app/.cache/transformers
    volumes:
      - .:/app
      - ./logs:/app/logs
      - transformers_cache:/app/.cache/transformers
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    shm_size: '2gb'

  redis:
    image: redis:6.2-alpine
    container_name: horizon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-/data
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 1.5G

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: horizon-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  redis: {}
  transformers_cache: {}